fix: Fails to load import map with module URL starting with "./"
lumeland/lume pull request #162
Opened 2022-01-10 13:57 UTC by aiotter

Lume fails to parse import map like following:
```js
{
  "imports": {
    "/": "./"
}

// Import map diagnostics:
//   - Invalid address "./" for the specifier key "/".
```

This is because Lume parses the given import map and convert it to data URI scheme.
Data URI scheme has no base URL, so parsing this specifier [fails](https://wicg.github.io/import-maps/#parse-a-url-like-import-specifier).

https://github.com/lumeland/lume/blob/5f0d950bcf20458e431f05ed84762a12d8b6548f/ci.ts#L45-L70

On deno environment, module URL which starts with "./" should be resolved to the import map's URL.
https://deno.land/manual/linking_to_external_code/import_maps

This PR fixes this issue by resolving those relative paths into file URI schemes.

2022-01-10 14:33 UTC, oscarotero requested changes

2022-01-12 03:00 UTC, aiotter commented on ci.ts
> +    ) => [key, value.startsWith("./") ? new URL(value, baseUrl).href : value]),
I didn't notice that is possible. You have great knowledge in dealing with JavaScript apis.

2022-01-12 03:04 UTC, aiotter commented
I've never seen `checkout@v2` fails.
Can you re-run the workflow? I believe this is a temporary problem.

2022-01-12 10:15 UTC, merged

2022-01-12 10:16 UTC, oscarotero commented
Thanks, it looks good.
I think the test error is not related with this.