Export hljs object
lumeland/lume pull request #169
Opened 2022-02-06 11:47 UTC by ihack2712

Ability to register languages is missing without it. Workaround is to import the dependency manually, but urgh..

2022-02-06 16:29 UTC, oscarotero commented
Hi. Thanks for your contribution.
By default, all languages are loaded, but I guess you want to register additional languages, right?

I'm not sure if import and customize hljs from the _config file is a good idea. What do you thing about adding this option to the plugin? Something like this:

```js
site.use(codeHighlight({
    languages: { javascript, css, html }
}));
```

Internally, the plugin could do this:

```js
for (const [name, lang] of Object.entries(options.languages)) {
    hljs.registerLanguage(name, lang);
}
```

Doing so, the plugin doesn't need to export anything to be configured. This is how all other plugins work.

2022-02-06 16:31 UTC, ihack2712 commented
That definetely works :)

2022-02-06 16:33 UTC, oscarotero commented
Nice! Do you like to implement it in this pull request? I'll be happy to merge it

2022-02-06 16:44 UTC, ihack2712 reviewed
Added languages property on highlightjs plugin options to register languages.

2022-02-06 16:44 UTC, ihack2712 commented on plugins/code_highlight.ts
> +export { hljs };
do not export, rather expose a languages property.

2022-02-06 16:46 UTC, ihack2712 reviewed
Added languages property on highlightjs plugin options to register languages.

2022-02-06 16:46 UTC, ihack2712 commented on plugins/code_highlight.ts
> +export { hljs };
It did not push changes from github editor...

2022-02-06 16:49 UTC, ihack2712 commented
Had a bit of troubles with the github.dev editor, it's probably smart to squash the commits for bettering naming :D

2022-02-06 16:56 UTC, oscarotero commented
There are some problems regarding to the typescript types. I think it's better to make changes in local and test it before commit.
Do you want to work on it? If not I can fix it, but I let you do it if you want.

2022-02-06 16:57 UTC, ihack2712 commented
Yeah, I am currently not on my PC with an editor, so I am using github.dev :)

2022-02-06 16:59 UTC, oscarotero commented
Ok, nice!
Let me know when you want to review and merge. No rush.

2022-02-06 17:02 UTC, ihack2712 commented
Should be good to go

2022-02-06 17:05 UTC, ihack2712 commented
Seems like the esm mirror doesn't export types :( I'll highlight.js source code and find the type manually.

2022-02-06 17:15 UTC, ihack2712 commented
Please re-run :)

2022-02-06 18:28 UTC, oscarotero requested changes

2022-02-06 18:28 UTC, oscarotero commented on plugins/code_highlight.ts
> +  if (userOptions && userOptions.languages) {
`userOptions` is merged into `options` variable, so this could be simplified with:

```suggestion
  if (options.languages) {
```

2022-02-07 10:17 UTC, oscarotero requested changes

2022-02-07 10:17 UTC, oscarotero commented on plugins/code_highlight.ts
> +    for (const [name, fn] of Object.entries(userOptions.languages)) {
missed change it here

2022-02-08 17:30 UTC, merged