Improve choosing plugins/dependencies in init script #358
lumeland/lume pull request #374
Opened 2023-02-09 04:54 UTC by tristanisham

## Description

## Related Issues

### Check List

- [ ] Have you read the
      [CODE OF CONDUCT](https://github.com/lumeland/lume/blob/master/CODE_OF_CONDUCT.md)
- [ ] Have you read the document
      [CONTRIBUTING](https://github.com/lumeland/lume/blob/master/CONTRIBUTING.md)

      - [ ] One pull request per feature. If you want to do more than one thing,
      send multiple pull request.
      - [ ] Write tests.
      - [ ] Run deno `fmt` to fix
      the code format before commit.
      - [ ] Document any change in the
      `CHANGELOG.md`.

2023-02-09 04:57 UTC, tristanisham commented
Unfortunately, this does change the appearance of the cli init script's plugin chooser (had to remove the URLs) for temporary compatibility. But this can be addressed in a future update. This choice only adds one dependency and doesn't require any new functions.

2023-02-09 17:58 UTC, oscarotero commented
Hi, thanks for this.
I like the new interface but I don't like it requires a new dependency (specially a NPM dependency).
I think a similar output can be achieved with Cliffy (the library I'm already using to build the CLI).

Take a look to this: https://cliffy.io/docs@v0.25.7/prompt

Or better, run this script:

```
deno run https://deno.land/x/cliffy@v0.25.7/examples/prompt/prompt_list.ts
```

2023-02-09 17:59 UTC, oscarotero requested changes
I think it's better to use the prompt function from Cliffy (https://cliffy.io/docs@v0.25.7/prompt)

2023-02-10 00:19 UTC, tristanisham commented
@oscarotero Updated to use the existing cliffy dependency. I also removed inquirer.

2023-02-10 10:47 UTC, oscarotero requested changes

2023-02-10 10:47 UTC, oscarotero commented on cli/init.ts
> +  const code = [`import lume from "https://deno.land/x/lume/mod.ts";`];
The URL here must be `lume/mod.ts`. It's resolved with the import map.

2023-02-10 10:47 UTC, oscarotero commented on cli/init.ts
> +      `import ${name} from "https://deno.land/x/lume/plugins/${name}.ts";`,
Same here, it must be `lume/plugins/${name}.ts`

2023-02-10 10:48 UTC, oscarotero commented
Thank you. Much better now!
I just let a couple of comments related to the URL to import the lume modules. You have changed the bare imports to full URLs, not sure why.

2023-02-10 14:30 UTC, tristanisham commented
@oscarotero I've changed it back to using the import map URLs. 👍🏼

2023-02-10 15:59 UTC, oscarotero commented
Thanks! The tests are failing due the code format. Can you run `deno fmt` and commit again?

2023-02-11 00:33 UTC, oscarotero approved these changes

2023-02-11 00:33 UTC, tristanisham commented
Updated the format and removed unused imports.

2023-02-11 00:37 UTC, merged

2023-02-11 00:37 UTC, oscarotero commented
Thank you!

2023-02-11 00:41 UTC, tristanisham commented
@oscarotero You're welcome! This was a really nice experience!